// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AssetAdjustResponse asset adjust response
//
// swagger:model assetAdjustResponse
type AssetAdjustResponse struct {

	// Operation ID
	// Example: op_daily_rewards_001
	// Required: true
	OperationID *string `json:"operation_id"`

	// Number of processed adjustments
	// Example: 1
	// Required: true
	ProcessedCount *int64 `json:"processed_count"`

	// Processing status
	// Example: recorded
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this asset adjust response
func (m *AssetAdjustResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProcessedCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AssetAdjustResponse) validateOperationID(formats strfmt.Registry) error {

	if err := validate.Required("operation_id", "body", m.OperationID); err != nil {
		return err
	}

	return nil
}

func (m *AssetAdjustResponse) validateProcessedCount(formats strfmt.Registry) error {

	if err := validate.Required("processed_count", "body", m.ProcessedCount); err != nil {
		return err
	}

	return nil
}

func (m *AssetAdjustResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this asset adjust response based on context it is used
func (m *AssetAdjustResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AssetAdjustResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetAdjustResponse) UnmarshalBinary(b []byte) error {
	var res AssetAdjustResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
