// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BatchMetrics batch metrics
//
// swagger:model batchMetrics
type BatchMetrics struct {

	// Actual processing efficiency
	// Example: 76.8
	ActualEfficiency float32 `json:"actual_efficiency,omitempty"`

	// Batch processing strategy
	// Example: medium_congestion_adaptive
	BatchStrategy string `json:"batch_strategy,omitempty"`

	// Number of operations in batch
	// Example: 25
	OperationCount int64 `json:"operation_count,omitempty"`
}

// Validate validates this batch metrics
func (m *BatchMetrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this batch metrics based on context it is used
func (m *BatchMetrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BatchMetrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BatchMetrics) UnmarshalBinary(b []byte) error {
	var res BatchMetrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
