// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BatchMintNFTsBody batch mint n f ts body
//
// swagger:model batchMintNFTsBody
type BatchMintNFTsBody struct {

	// batch preferences
	BatchPreferences *BatchPreference `json:"batch_preferences,omitempty"`

	// Chain ID
	// Example: 11155111
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// Collection identifier
	// Example: cpop_nft_collection_1
	// Required: true
	CollectionID *string `json:"collection_id"`

	// mint operations
	// Required: true
	MintOperations []*NFTMintOperation `json:"mint_operations"`

	// Operation ID
	// Example: 550e8400-e29b-41d4-a716-446655440001
	// Required: true
	OperationID *string `json:"operation_id"`
}

// Validate validates this batch mint n f ts body
func (m *BatchMintNFTsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBatchPreferences(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCollectionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMintOperations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOperationID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BatchMintNFTsBody) validateBatchPreferences(formats strfmt.Registry) error {
	if swag.IsZero(m.BatchPreferences) { // not required
		return nil
	}

	if m.BatchPreferences != nil {
		if err := m.BatchPreferences.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("batch_preferences")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("batch_preferences")
			}
			return err
		}
	}

	return nil
}

func (m *BatchMintNFTsBody) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *BatchMintNFTsBody) validateCollectionID(formats strfmt.Registry) error {

	if err := validate.Required("collection_id", "body", m.CollectionID); err != nil {
		return err
	}

	return nil
}

func (m *BatchMintNFTsBody) validateMintOperations(formats strfmt.Registry) error {

	if err := validate.Required("mint_operations", "body", m.MintOperations); err != nil {
		return err
	}

	for i := 0; i < len(m.MintOperations); i++ {
		if swag.IsZero(m.MintOperations[i]) { // not required
			continue
		}

		if m.MintOperations[i] != nil {
			if err := m.MintOperations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mint_operations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("mint_operations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BatchMintNFTsBody) validateOperationID(formats strfmt.Registry) error {

	if err := validate.Required("operation_id", "body", m.OperationID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this batch mint n f ts body based on the context it is used
func (m *BatchMintNFTsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBatchPreferences(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMintOperations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BatchMintNFTsBody) contextValidateBatchPreferences(ctx context.Context, formats strfmt.Registry) error {

	if m.BatchPreferences != nil {
		if err := m.BatchPreferences.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("batch_preferences")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("batch_preferences")
			}
			return err
		}
	}

	return nil
}

func (m *BatchMintNFTsBody) contextValidateMintOperations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MintOperations); i++ {

		if m.MintOperations[i] != nil {
			if err := m.MintOperations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mint_operations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("mint_operations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BatchMintNFTsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BatchMintNFTsBody) UnmarshalBinary(b []byte) error {
	var res BatchMintNFTsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
