// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateAccountResponse create account response
//
// swagger:model createAccountResponse
type CreateAccountResponse struct {

	// Generated AA account address
	// Example: 0x742d35Cc6634C0532925a3b8D238b45D2F78d8F3
	AaAddress string `json:"aa_address,omitempty"`

	// Whether account was created successfully
	// Example: true
	AccountCreated bool `json:"account_created,omitempty"`

	// Binding status
	// Example: success
	BindingStatus string `json:"binding_status,omitempty"`

	// Chain ID
	// Example: 56
	ChainID int64 `json:"chain_id,omitempty"`

	// Deployment status
	// Example: false
	IsDeployed bool `json:"is_deployed,omitempty"`

	// Owner EOA address
	// Example: 0x1234567890123456789012345678901234567890
	Owner string `json:"owner,omitempty"`

	// User identifier
	// Example: user_123
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this create account response
func (m *CreateAccountResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create account response based on context it is used
func (m *CreateAccountResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateAccountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAccountResponse) UnmarshalBinary(b []byte) error {
	var res CreateAccountResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
