// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NFTAttribute n f t attribute
//
// swagger:model nFTAttribute
type NFTAttribute struct {

	// Rarity percentage
	// Example: 15.5
	RarityPercentage float32 `json:"rarity_percentage,omitempty"`

	// Attribute trait type
	// Example: Background
	// Required: true
	TraitType *string `json:"trait_type"`

	// Attribute value
	// Example: Blue
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this n f t attribute
func (m *NFTAttribute) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTraitType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NFTAttribute) validateTraitType(formats strfmt.Registry) error {

	if err := validate.Required("trait_type", "body", m.TraitType); err != nil {
		return err
	}

	return nil
}

func (m *NFTAttribute) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this n f t attribute based on context it is used
func (m *NFTAttribute) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NFTAttribute) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NFTAttribute) UnmarshalBinary(b []byte) error {
	var res NFTAttribute
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
