// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PerformanceMetrics performance metrics
//
// swagger:model performanceMetrics
type PerformanceMetrics struct {

	// Average processing time in milliseconds
	// Example: 2150
	AverageProcessingTimeMs int64 `json:"average_processing_time_ms,omitempty"`

	// Overall efficiency rating (0-100)
	// Example: 82.6
	EfficiencyRating float32 `json:"efficiency_rating,omitempty"`

	// Gas saved percentage compared to individual transactions
	// Example: 78.2
	GasSavedPercentage float32 `json:"gas_saved_percentage,omitempty"`

	// Number of samples used for this analysis
	// Example: 156
	SampleSize int64 `json:"sample_size,omitempty"`
}

// Validate validates this performance metrics
func (m *PerformanceMetrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this performance metrics based on context it is used
func (m *PerformanceMetrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PerformanceMetrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PerformanceMetrics) UnmarshalBinary(b []byte) error {
	var res PerformanceMetrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
