// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateChainRequest update chain request
//
// swagger:model updateChainRequest
type UpdateChainRequest struct {

	// Account manager contract address
	// Example: 0xabcdefabcdefabcdefabcdefabcdefabcdefabcd
	AccountManagerAddress string `json:"account_manager_address,omitempty"`

	// CPOP token contract address
	// Example: 0x1234567890123456789012345678901234567890
	CpopTokenAddress string `json:"cpop_token_address,omitempty"`

	// EntryPoint contract address
	// Example: 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
	EntryPointAddress string `json:"entry_point_address,omitempty"`

	// Block explorer URL
	// Example: https://updated-explorer.example.com
	ExplorerURL string `json:"explorer_url,omitempty"`

	// Whether chain is enabled
	// Example: false
	IsEnabled bool `json:"is_enabled,omitempty"`

	// Master aggregator contract address
	// Example: 0x0987654321098765432109876543210987654321
	MasterAggregatorAddress string `json:"master_aggregator_address,omitempty"`

	// Maximum batch size
	// Example: 50
	MaxBatchSize int64 `json:"max_batch_size,omitempty"`

	// Minimum batch size
	// Example: 15
	MinBatchSize int64 `json:"min_batch_size,omitempty"`

	// Chain name
	// Example: Updated Chain Name
	Name string `json:"name,omitempty"`

	// Optimal batch size for processing
	// Example: 30
	OptimalBatchSize int64 `json:"optimal_batch_size,omitempty"`

	// RPC endpoint URL
	// Example: https://updated-rpc.example.com
	RPCURL string `json:"rpc_url,omitempty"`

	// Chain short name
	// Example: updated
	ShortName string `json:"short_name,omitempty"`
}

// Validate validates this update chain request
func (m *UpdateChainRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update chain request based on context it is used
func (m *UpdateChainRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateChainRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateChainRequest) UnmarshalBinary(b []byte) error {
	var res UpdateChainRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
