swagger: "2.0"
info:
  title: github.com/hzbay/chain-bridge
  version: 0.1.0
paths:
  # 1. 建立WebSocket连接（实时通知）
  /subscribe:
    get:
      tags:
        - application
      summary: Establish WebSocket connection
      description: "建立应用级WebSocket连接，用于接收实时通知"
      operationId: subscribeNotifications
      security:
        - Management: [ ]
      parameters:
        - name: events
          in: query
          description: Event types to subscribe to (comma-separated)
          required: false
          type: string
        - name: chains
          in: query
          description: Chain IDs to monitor (comma-separated)
          required: false
          type: string
        - name: app_id
          in: query
          description: Application identifier
          required: true
          type: string
      responses:
        "101":
          description: WebSocket connection established
          schema:
            type: object
            properties:
              type:
                type: string
                example: "connection_established"
              data:
                type: object
                properties:
                  connection_id:
                    type: string
                    example: "conn_abc123"
                  app_id:
                    type: string
                    example: "your_app_id"
                  subscribed_events:
                    type: array
                    items:
                      type: string
                    example: [ "transaction", "batch", "balance" ]
                  subscribed_chains:
                    type: array
                    items:
                      type: integer
                    example: [ 56, 1 ]
                  rate_limit:
                    type: string
                    example: "1000 events/minute"
          examples:
            application/json:
              type: "connection_established"
              data:
                connection_id: "conn_abc123"
                app_id: "your_app_id"
                subscribed_events: [ "transaction", "batch", "balance" ]
                subscribed_chains: [ 56, 1 ]
                rate_limit: "1000 events/minute"
        "400":
          description: Invalid connection parameters
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
          examples:
            application/json:
              message: "Invalid app_id parameter"
              errors:
                - field: "app_id"
                  code: "INVALID_APP_ID"
                  message: "app_id is required for WebSocket connection"
        "401":
          $ref: "../definitions/errors.yml#/responses/UnauthorizedError"
        "500":
          $ref: "../definitions/errors.yml#/responses/InternalError"