swagger: "2.0"
info:
  title: github.com/hzbay/chain-bridge
  version: 0.1.0
paths:
  # 1. 获取用户资产总览
  /users/{user_id}/assets:
    get:
      tags:
        - cpop
      summary: Get user assets overview
      description: "获取用户跨链资产概览，包含批量处理状态信息"
      operationId: getUserAssets
      security:
        - Management: []
      parameters:
        - name: user_id
          in: path
          description: User identifier
          required: true
          type: string
      responses:
        "200":
          description: User assets retrieved successfully
          schema:
            type: object
            properties:
              data:
                $ref: "../definitions/assets.yml#/definitions/AssetsResponse"
              batch_info:
                $ref: "../definitions/assets.yml#/definitions/BatchInfo"
        "400":
          $ref: "../definitions/errors.yml#/responses/BadRequestError"
        "401":
          $ref: "../definitions/errors.yml#/responses/UnauthorizedError"
        "404":
          description: User not found
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "500":
          $ref: "../definitions/errors.yml#/responses/InternalError"

  # 2. 资产调整接口
  /assets/adjust:
    post:
      tags:
        - cpop
      summary: Adjust user assets
      description: "批量调整用户资产余额（铸造/销毁操作），支持智能批处理"
      operationId: adjustAssets
      security:
        - Management: []
      parameters:
        - name: request
          in: body
          description: Asset adjustment request
          required: true
          schema:
            $ref: "../definitions/assets.yml#/definitions/AssetAdjustRequest"
      responses:
        "200":
          description: Asset adjustment recorded successfully
          schema:
            type: object
            properties:
              data:
                $ref: "../definitions/assets.yml#/definitions/AssetAdjustResponse"
              batch_info:
                $ref: "../definitions/assets.yml#/definitions/BatchInfo"
        "400":
          description: Invalid request parameters
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "401":
          $ref: "../definitions/errors.yml#/responses/UnauthorizedError"
        "422":
          description: Insufficient balance or business rule violation
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "500":
          $ref: "../definitions/errors.yml#/responses/InternalError"