swagger: "2.0"
info:
  title: github.com/hzbay/chain-bridge
  version: 0.1.0
paths:
  # 1. 获取用户钱包信息
  /wallet/{user_id}:
    get:
      tags:
        - cpop
      summary: Get user wallet information
      description: "获取用户跨链钱包信息"
      operationId: getUserWallet
      security:
        - Bearer: []
      parameters:
        - name: user_id
          in: path
          description: User identifier
          required: true
          type: string
      responses:
        "200":
          description: User wallet information retrieved successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/WalletResponse"
        "400":
          $ref: "../definitions/errors.yml#/responses/BadRequestError"
        "401":
          $ref: "../definitions/errors.yml#/responses/UnauthorizedError"
        "404":
          description: User or wallet not found
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "500":
          $ref: "../definitions/errors.yml#/responses/InternalError"

  # 2. 创建用户钱包
  /wallet/{user_id}/create:
    post:
      tags:
        - cpop
      summary: Create user wallet
      description: "为用户在指定链上创建新的账户抽象钱包"
      operationId: createUserWallet
      security:
        - Bearer: []
      parameters:
        - name: user_id
          in: path
          description: User identifier
          required: true
          type: string
        - name: request
          in: body
          description: Wallet creation request
          required: true
          schema:
            $ref: "../definitions/wallet.yml#/definitions/CreateWalletRequest"
      responses:
        "200":
          description: Wallet created successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/CreateWalletResponse"
        "400":
          description: Invalid request parameters
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "401":
          $ref: "../definitions/errors.yml#/responses/UnauthorizedError"
        "409":
          description: Wallet already exists
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "422":
          description: Chain not supported or disabled
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "500":
          $ref: "../definitions/errors.yml#/responses/InternalError"

  # 3. 部署用户钱包
  /wallet/{user_id}/deploy:
    post:
      tags:
        - cpop
      summary: Deploy user wallet
      description: "将用户已创建的账户抽象钱包部署到指定链上"
      operationId: deployUserWallet
      security:
        - Bearer: []
      parameters:
        - name: user_id
          in: path
          description: User identifier
          required: true
          type: string
        - name: request
          in: body
          description: Wallet deployment request
          required: true
          schema:
            $ref: "../definitions/wallet.yml#/definitions/DeployWalletRequest"
      responses:
        "200":
          description: Wallet deployment initiated successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/DeployWalletResponse"
        "400":
          description: Invalid request parameters
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "401":
          $ref: "../definitions/errors.yml#/responses/UnauthorizedError"
        "404":
          description: User or wallet not found
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "409":
          description: Wallet already deployed
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "422":
          description: Chain not supported or wallet not ready for deployment
          schema:
            $ref: "../definitions/errors.yml#/definitions/APIError"
        "500":
          $ref: "../definitions/errors.yml#/responses/InternalError"