// Code generated by go-swagger; DO NOT EDIT.

package cpop_mgmt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteTokenParams creates a new DeleteTokenParams object
// no default values defined in spec.
func NewDeleteTokenParams() DeleteTokenParams {

	return DeleteTokenParams{}
}

// DeleteTokenParams contains all the bound params for the delete token operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteToken
type DeleteTokenParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The token ID
	  Required: true
	  In: path
	*/
	TokenID int64 `param:"token_id"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteTokenParams() beforehand.
func (o *DeleteTokenParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTokenID, rhkTokenID, _ := route.Params.GetOK("token_id")
	if err := o.bindTokenID(rTokenID, rhkTokenID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteTokenParams) Validate(formats strfmt.Registry) error {
	var res []error

	// token_id
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTokenID binds and validates parameter TokenID from path.
func (o *DeleteTokenParams) bindTokenID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("token_id", "path", "int64", raw)
	}
	o.TokenID = value

	return nil
}
