// Code generated by go-swagger; DO NOT EDIT.

package cpop_mgmt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hzbay/chain-bridge/internal/types"
)

// NewUpdateTokenParams creates a new UpdateTokenParams object
// no default values defined in spec.
func NewUpdateTokenParams() UpdateTokenParams {

	return UpdateTokenParams{}
}

// UpdateTokenParams contains all the bound params for the update token operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateToken
type UpdateTokenParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Token update request
	  Required: true
	  In: body
	*/
	Request *types.UpdateTokenRequest
	/*The token ID
	  Required: true
	  In: path
	*/
	TokenID int64 `param:"token_id"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateTokenParams() beforehand.
func (o *UpdateTokenParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.UpdateTokenRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("request", "body", ""))
			} else {
				res = append(res, errors.NewParseError("request", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Request = &body
			}
		}
	} else {
		res = append(res, errors.Required("request", "body", ""))
	}
	rTokenID, rhkTokenID, _ := route.Params.GetOK("token_id")
	if err := o.bindTokenID(rTokenID, rhkTokenID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateTokenParams) Validate(formats strfmt.Registry) error {
	var res []error

	// request
	// Required: true

	// body is validated in endpoint
	//if err := o.Request.Validate(formats); err != nil {
	//  res = append(res, err)
	//}

	// token_id
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTokenID binds and validates parameter TokenID from path.
func (o *UpdateTokenParams) bindTokenID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("token_id", "path", "int64", raw)
	}
	o.TokenID = value

	return nil
}
