// Code generated by go-swagger; DO NOT EDIT.

package cpop_mgmt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hzbay/chain-bridge/internal/types"
)

// NewUpdateChainParams creates a new UpdateChainParams object
// no default values defined in spec.
func NewUpdateChainParams() UpdateChainParams {

	return UpdateChainParams{}
}

// UpdateChainParams contains all the bound params for the update chain operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateChain
type UpdateChainParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The blockchain network ID
	  Required: true
	  In: path
	*/
	ChainID int64 `param:"chain_id"`
	/*Chain update request
	  Required: true
	  In: body
	*/
	Request *types.UpdateChainRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateChainParams() beforehand.
func (o *UpdateChainParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rChainID, rhkChainID, _ := route.Params.GetOK("chain_id")
	if err := o.bindChainID(rChainID, rhkChainID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.UpdateChainRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("request", "body", ""))
			} else {
				res = append(res, errors.NewParseError("request", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Request = &body
			}
		}
	} else {
		res = append(res, errors.Required("request", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateChainParams) Validate(formats strfmt.Registry) error {
	var res []error

	// chain_id
	// Required: true
	// Parameter is provided by construction from the route

	// request
	// Required: true

	// body is validated in endpoint
	//if err := o.Request.Validate(formats); err != nil {
	//  res = append(res, err)
	//}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChainID binds and validates parameter ChainID from path.
func (o *UpdateChainParams) bindChainID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("chain_id", "path", "int64", raw)
	}
	o.ChainID = value

	return nil
}
