// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserWallets(t *testing.T) {
	t.Parallel()

	query := UserWallets()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserWalletsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserWalletsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserWallets().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserWalletsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserWalletSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserWalletsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserWalletExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserWallet exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserWalletExists to return true, but got false.")
	}
}

func testUserWalletsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userWalletFound, err := FindUserWallet(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userWalletFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserWalletsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserWallets().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserWalletsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserWallets().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserWalletsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userWalletOne := &UserWallet{}
	userWalletTwo := &UserWallet{}
	if err = randomize.Struct(seed, userWalletOne, userWalletDBTypes, false, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}
	if err = randomize.Struct(seed, userWalletTwo, userWalletDBTypes, false, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userWalletOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userWalletTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserWallets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserWalletsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userWalletOne := &UserWallet{}
	userWalletTwo := &UserWallet{}
	if err = randomize.Struct(seed, userWalletOne, userWalletDBTypes, false, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}
	if err = randomize.Struct(seed, userWalletTwo, userWalletDBTypes, false, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userWalletOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userWalletTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testUserWalletsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserWalletsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userWalletColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserWalletToOneChainUsingChain(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserWallet
	var foreign Chain

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userWalletDBTypes, false, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, chainDBTypes, false, chainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chain struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ChainID = foreign.ChainID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Chain().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ChainID != foreign.ChainID {
		t.Errorf("want: %v, got %v", foreign.ChainID, check.ChainID)
	}

	slice := UserWalletSlice{&local}
	if err = local.L.LoadChain(ctx, tx, false, (*[]*UserWallet)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Chain == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Chain = nil
	if err = local.L.LoadChain(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Chain == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testUserWalletToOneSetOpChainUsingChain(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserWallet
	var b, c Chain

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userWalletDBTypes, false, strmangle.SetComplement(userWalletPrimaryKeyColumns, userWalletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, chainDBTypes, false, strmangle.SetComplement(chainPrimaryKeyColumns, chainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, chainDBTypes, false, strmangle.SetComplement(chainPrimaryKeyColumns, chainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Chain{&b, &c} {
		err = a.SetChain(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Chain != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserWallets[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ChainID != x.ChainID {
			t.Error("foreign key was wrong value", a.ChainID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ChainID))
		reflect.Indirect(reflect.ValueOf(&a.ChainID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ChainID != x.ChainID {
			t.Error("foreign key was wrong value", a.ChainID, x.ChainID)
		}
	}
}

func testUserWalletsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserWalletsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserWalletSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserWalletsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserWallets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userWalletDBTypes = map[string]string{`ID`: `integer`, `UserID`: `uuid`, `ChainID`: `bigint`, `AaAddress`: `character`, `Owner`: `character`, `IsDeployed`: `boolean`, `DeploymentTXHash`: `character`, `MasterSigner`: `character`, `CreatedAt`: `timestamp with time zone`}
	_                 = bytes.MinRead
)

func testUserWalletsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userWalletPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userWalletAllColumns) == len(userWalletPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserWalletsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userWalletAllColumns) == len(userWalletPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserWallet{}
	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userWalletDBTypes, true, userWalletPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userWalletAllColumns, userWalletPrimaryKeyColumns) {
		fields = userWalletAllColumns
	} else {
		fields = strmangle.SetComplement(
			userWalletAllColumns,
			userWalletPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserWalletSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserWalletsUpsert(t *testing.T) {
	t.Parallel()

	if len(userWalletAllColumns) == len(userWalletPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserWallet{}
	if err = randomize.Struct(seed, &o, userWalletDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserWallet: %s", err)
	}

	count, err := UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userWalletDBTypes, false, userWalletPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserWallet struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserWallet: %s", err)
	}

	count, err = UserWallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
