# This is our base swagger file and the primary mixin target.
# Everything in definitions|paths/*.yml will be mixed through
# and finally flattened into the actual swagger.yml in this dir.
consumes:
  - application/json
produces:
  - application/json
swagger: "2.0"
info:
  title: github.com/hzbay/chain-bridge
  version: 0.1.0
  description: API documentation
paths: {}
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |-
      Access token for application access, **must** include "Bearer " prefix.
      Example: `Bearer b4a94a42-3ea2-4af3-9699-8bcbfee6e6d2`
    x-keyPrefix: "Bearer "
  Management:
    type: apiKey
    in: query
    description: Management secret, used for monitoring and infrastructure related calls
    name: mgmt-secret
definitions:
  # Any definitions that are not yet used within paths/*.yml are automatically removed from the resulting swagger.yml.
  # You may reference some definitions that you *always* want to be included here.
  # --
  # Always include nullables so we can test deserialization
  nullables:
    $ref: "../definitions/nullable.yml#/definitions/Nullables"
  # Always include orderDir so we can test binding it to db queries directly.
  orderDir:
    type: string
    enum:
      - asc
      - desc
  # Chain bridge definitions
  Chain:
    $ref: "../definitions/chainbridge-common.yml#/definitions/Chain"
  BatchConfig:
    $ref: "../definitions/chainbridge-common.yml#/definitions/BatchConfig"
  # Chains definitions
  UpdateChainBatchConfigBody:
    $ref: "../definitions/chains.yml#/definitions/UpdateChainBatchConfigBody"
  BatchConfigUpdateResponse:
    $ref: "../definitions/chains.yml#/definitions/BatchConfigUpdateResponse"
  CacheRefreshResponse:
    $ref: "../definitions/chains.yml#/definitions/CacheRefreshResponse"
  ChainResponse:
    $ref: "../definitions/chains.yml#/definitions/ChainResponse"
  ChainsResponse:
    $ref: "../definitions/chains.yml#/definitions/ChainsResponse"
  createChainRequest:
    $ref: "../definitions/chains.yml#/definitions/CreateChainRequest"
  updateChainRequest:
    $ref: "../definitions/chains.yml#/definitions/UpdateChainRequest"
  chainCreateResponse:
    $ref: "../definitions/chains.yml#/definitions/ChainCreateResponse"
  chainUpdateResponse:
    $ref: "../definitions/chains.yml#/definitions/ChainUpdateResponse"
  chainDeleteResponse:
    $ref: "../definitions/chains.yml#/definitions/ChainDeleteResponse"
  chainToggleStatusResponse:
    $ref: "../definitions/chains.yml#/definitions/ChainToggleStatusResponse"
  # Monitoring definitions
  queueMetricsResponse:
    $ref: "../definitions/monitoring.yml#/definitions/queueMetricsResponse"
  queueStatsResponse:
    $ref: "../definitions/monitoring.yml#/definitions/queueStatsResponse"
  queueHealthResponse:
    $ref: "../definitions/monitoring.yml#/definitions/queueHealthResponse"
  optimizationRecommendationResponse:
    $ref: "../definitions/monitoring.yml#/definitions/optimizationRecommendationResponse"
  userOptimizationRecommendationResponse:
    $ref: "../definitions/monitoring.yml#/definitions/userOptimizationRecommendationResponse"
  paymentEventsStatsResponse:
    $ref: "../definitions/monitoring.yml#/definitions/paymentEventsStatsResponse"
  paymentEventsReloadResponse:
    $ref: "../definitions/monitoring.yml#/definitions/paymentEventsReloadResponse"
  # Assets definitions
  assetAdjustResponse:
    $ref: "../definitions/assets.yml#/definitions/AssetAdjustResponse"
  assetAdjustCompleteResponse:
    $ref: "../definitions/assets.yml#/definitions/AssetAdjustCompleteResponse"
  assetsResponse:
    $ref: "../definitions/assets.yml#/definitions/AssetsResponse"
  batchInfo:
    $ref: "../definitions/assets.yml#/definitions/BatchInfo"
  userAssetsCompleteResponse:
    $ref: "../definitions/assets.yml#/definitions/UserAssetsCompleteResponse"
  # Batch definitions
  batchStatusResponse:
    $ref: "../definitions/batch.yml#/definitions/BatchStatusResponse"
  # Transfer definitions  
  transferResponse:
    $ref: "../definitions/transfer.yml#/definitions/TransferResponse"
  transactionHistoryResponse:
    $ref: "../definitions/transfer.yml#/definitions/TransactionHistoryResponse"
  userTransactionHistoryResponse:
    $ref: "../definitions/transfer.yml#/definitions/UserTransactionHistoryResponse"
  # Account definitions
  accountResponse:
    $ref: "../definitions/account.yml#/definitions/AccountResponse"
  createAccountResponse:
    $ref: "../definitions/account.yml#/definitions/CreateAccountResponse"
  deployAccountResponse:
    $ref: "../definitions/account.yml#/definitions/DeployAccountResponse"
  # Tokens definitions
  tokenResponse:
    $ref: "../definitions/tokens.yml#/definitions/TokenResponse"
  tokensResponse:
    $ref: "../definitions/tokens.yml#/definitions/TokensResponse"
  createTokenRequest:
    $ref: "../definitions/tokens.yml#/definitions/CreateTokenRequest"
  updateTokenRequest:
    $ref: "../definitions/tokens.yml#/definitions/UpdateTokenRequest"
  tokenConfigUpdateResponse:
    $ref: "../definitions/tokens.yml#/definitions/TokenConfigUpdateResponse"
  tokenCreateResponse:
    $ref: "../definitions/tokens.yml#/definitions/TokenCreateResponse"
  tokenDeleteResponse:
    $ref: "../definitions/tokens.yml#/definitions/TokenDeleteResponse"
