# ChainBridge Application Layer Models

BatchRewardRequest:
  type: "object"
  required:
    - "chain_id"
    - "recipients"
  properties:
    chain_id:
      type: "integer"
      format: "int64"
      description: "Blockchain network ID"
      example: 1
    recipients:
      type: "array"
      minItems: 1
      maxItems: 1000
      items:
        $ref: "#/definitions/RewardRecipient"
    activity_id:
      type: "string"
      description: "Activity identifier for tracking"
      example: "activity_weekly_reward_2024_01"

RewardRecipient:
  type: "object"
  required:
    - "user_id"
    - "amount"
  properties:
    user_id:
      type: "string"
      format: "uuid"
      description: "Recipient user ID"
    amount:
      type: "string"
      pattern: "^[0-9]+\\.?[0-9]*$"
      description: "CPOP reward amount"
      example: "100.0"
    reason:
      type: "string"
      maxLength: 256
      description: "Reason for reward"
      example: "Weekly activity completion"

BatchRewardResponse:
  type: "object"
  required:
    - "batch_id"
    - "status"
    - "total_recipients"
    - "total_amount"
  properties:
    batch_id:
      type: "string"
      format: "uuid"
      description: "Batch processing ID"
    status:
      type: "string"
      enum: ["pending", "processing", "completed", "failed"]
      description: "Batch processing status"
    total_recipients:
      type: "integer"
      description: "Number of recipients"
      example: 150
    total_amount:
      type: "string"
      description: "Total CPOP amount distributed"
      example: "15000.0"
    estimated_completion:
      type: "integer"
      description: "Estimated completion time in seconds"
      example: 120
    gas_savings_percent:
      type: "number"
      format: "float"
      description: "Gas savings percentage vs individual transfers"
      example: 82.5