# ChainBridge Assets Data Models
# 资产管理相关的数据模型定义

swagger: "2.0"
info:
  title: github.com/hzbay/chain-bridge
  version: 0.1.0
paths: {}
definitions:
  # 资产信息模型
  AssetInfo:
    type: object
    required: [chain_id, symbol, confirmed_balance, pending_balance, locked_balance]
    properties:
      chain_id:
        type: integer
        format: int64
        description: "Chain ID"
        example: 56
      chain_name:
        type: string
        description: "Chain name"
        example: "BSC"
      symbol:
        type: string
        description: "Token symbol"
        example: "CPOP"
      name:
        type: string
        description: "Token name"
        example: "ChainBridge PoP Token"
      contract_address:
        type: string
        description: "Token contract address"
        example: "0x742d35Cc6634C0532925a3b8D238b45D2F78d8F3"
      decimals:
        type: integer
        description: "Token decimals"
        example: 18
      confirmed_balance:
        type: string
        description: "Confirmed balance on-chain"
        example: "5000.0"
      pending_balance:
        type: string
        description: "Balance including pending changes"
        example: "5050.0"
      locked_balance:
        type: string
        description: "Locked balance"
        example: "0.0"
      balance_usd:
        type: number
        format: float
        description: "Balance in USD"
        example: 250.0
      sync_status:
        type: string
        enum: [synced, syncing, pending]
        description: "Synchronization status"
        default: synced

  # NFT属性
  NFTAttribute:
    type: object
    required: [trait_type, value]
    properties:
      trait_type:
        type: string
        description: "Attribute trait type"
        example: "Background"
      value:
        type: string
        description: "Attribute value"
        example: "Blue"
      rarity_percentage:
        type: number
        format: float
        description: "Rarity percentage"
        example: 15.5

  # NFT元数据
  NFTMetadata:
    type: object
    properties:
      name:
        type: string
        description: "NFT name"
        example: "Genesis Token #1"
      description:
        type: string
        description: "NFT description"
        example: "A rare genesis collection NFT"
      image:
        type: string
        description: "NFT image URL"
        example: "https://example.com/nft/1.png"
      external_url:
        type: string
        description: "External URL"
        example: "https://example.com/nft/1"
      attributes:
        type: array
        items:
          $ref: "#/definitions/NFTAttribute"

  # NFT物品
  NFTItem:
    type: object
    required: [token_id]
    properties:
      token_id:
        type: string
        description: "NFT Token ID"
        example: "1"
      meta:
        $ref: "#/definitions/NFTMetadata"
      estimated_value_usd:
        type: number
        format: float
        description: "Estimated value in USD"
        example: 100.0
      last_transfer_date:
        type: string
        format: date-time
        description: "Last transfer date"
        example: "2024-01-15T10:30:00Z"

  # NFT集合信息
  NFTCollectionInfo:
    type: object
    required: [collection_id, collection_name, chain_id, total_count, items]
    properties:
      collection_id:
        type: string
        description: "Collection identifier"
        example: "cpop_genesis"
      collection_name:
        type: string
        description: "Collection name"
        example: "CPOP Genesis NFTs"
      contract_address:
        type: string
        description: "Contract address"
        example: "0x1234567890123456789012345678901234567890"
      chain_id:
        type: integer
        format: int64
        description: "Chain ID"
        example: 56
      chain_name:
        type: string
        description: "Chain name"
        example: "BSC"
      total_count:
        type: integer
        description: "Total NFT count owned by user"
        example: 5
      floor_price_usd:
        type: number
        format: float
        description: "Floor price in USD"
        example: 100.0
      total_value_usd:
        type: number
        format: float
        description: "Total collection value in USD"
        example: 500.0
      items:
        type: array
        items:
          $ref: "#/definitions/NFTItem"

  # 用户资产概览响应（扩展版本，包含NFT资产）
  AssetsResponse:
    type: object
    required: [user_id, total_value_usd, assets]
    properties:
      user_id:
        type: string
        description: "User identifier"
        example: "user_123"
      total_value_usd:
        type: number
        format: float
        description: "Total portfolio value in USD (tokens + NFTs)"
        example: 1750.50
      token_value_usd:
        type: number
        format: float
        description: "Token assets value in USD"
        example: 1250.50
      nft_value_usd:
        type: number
        format: float
        description: "NFT assets value in USD"
        example: 500.0
      assets:
        type: array
        items:
          $ref: "#/definitions/AssetInfo"
      nft_assets:
        type: array
        items:
          $ref: "#/definitions/NFTCollectionInfo"

  # 资产调整项
  AssetAdjustment:
    type: object
    required: [user_id, chain_id, token_symbol, amount, business_type, reason_type]
    properties:
      user_id:
        type: string
        description: "User ID"
        example: "user_123"
      chain_id:
        type: integer
        format: int64
        description: "Chain ID"
        example: 56
      token_symbol:
        type: string
        description: "Token symbol"
        example: "CPOP"
      amount:
        type: string
        description: "Adjustment amount (+/-)"
        example: "+100.0"
      business_type:
        type: string
        enum: [reward, gas_fee, consumption, refund]
        description: "Business type"
      reason_type:
        type: string
        description: "Reason type"
        example: "daily_checkin"
      reason_detail:
        type: string
        description: "Detailed reason"
        example: "Daily check-in reward"

  # 批量处理偏好
  BatchPreference:
    type: object
    properties:
      priority:
        type: string
        enum: [low, normal, high]
        description: "Processing priority"
        default: normal
      max_wait_time:
        type: string
        description: "Maximum wait time"
        example: "15m"

  # 资产调整请求
  AssetAdjustRequest:
    type: object
    required: [operation_id, adjustments]
    properties:
      operation_id:
        type: string
        description: "Operation ID"
        example: "op_daily_rewards_001"
      adjustments:
        type: array
        items:
          $ref: "#/definitions/AssetAdjustment"
      batch_preference:
        $ref: "#/definitions/BatchPreference"

  # 资产调整响应
  AssetAdjustResponse:
    type: object
    required: [operation_id, processed_count, status]
    properties:
      operation_id:
        type: string
        description: "Operation ID"
        example: "op_daily_rewards_001"
      processed_count:
        type: integer
        description: "Number of processed adjustments"
        example: 1
      status:
        type: string
        description: "Processing status"
        example: "recorded"

  # 批量信息
  BatchInfo:
    type: object
    properties:
      pending_operations:
        type: integer
        description: "Number of pending operations"
        example: 3
      next_batch_estimate:
        type: string
        description: "Next batch processing estimate"
        example: "5-10 minutes"
      will_be_batched:
        type: boolean
        description: "Whether will be processed in batch"
        example: true
      batch_id:
        type: string
        description: "Batch ID"
        example: "batch_daily_rewards_20241215"
      current_batch_size:
        type: integer
        description: "Current batch size"
        example: 24
      optimal_batch_size:
        type: integer
        description: "Optimal batch size"
        example: 25
      expected_efficiency:
        type: string
        description: "Expected efficiency"
        example: "75-77%"
      estimated_gas_savings:
        type: string
        description: "Estimated gas savings"
        example: "156.80 USD"
      batch_type:
        type: string
        description: "Batch operation type"
        example: "batchTransferFrom"

  # 资产调整完整响应 (包含data和batch_info)
  AssetAdjustCompleteResponse:
    type: object
    required: [data, batch_info]
    properties:
      data:
        $ref: "#/definitions/AssetAdjustResponse"
      batch_info:
        $ref: "#/definitions/BatchInfo"

  # 用户资产完整响应 (包含data和batch_info)
  UserAssetsCompleteResponse:
    type: object
    required: [data, batch_info]
    properties:
      data:
        $ref: "#/definitions/AssetsResponse"
      batch_info:
        $ref: "#/definitions/BatchInfo"